version: '3.8'
services:
  atlas-php:
    container_name: atlas-api
    image: php:8.0-apache
    build:
      context: ./app/
      dockerfile: Dockerfile
    depends_on:
      - atlas-db
    volumes:
      - ./app/src:/var/www/html/
    ports:
      - 8000:80
  atlas-db:
    container_name: atlas-db
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_DATABASE: atlas
        MYSQL_USER: atlas
        MYSQL_PASSWORD: 123456
    ports:
        - "9906:3306"
  atlas-pma:
    container_name: atlas-pma
    image: phpmyadmin/phpmyadmin
    ports:
        - '6789:80'
    restart: always
    environment:
        PMA_HOST: atlas-db
    depends_on:
        - atlas-db